# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Walkability_Index
                                 A QGIS plugin
 Helps in calculating the walkabilty score of a region
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-07
        copyright            : (C) 2022 by Niranjan P
        email                : niranjanp.191cv138@nitk.edu.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Walkability_Index class from file Walkability_Index.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .walkability import Walkability_Index
    return Walkability_Index(iface)
